apiVersion: v1
kind: Pod
metadata:
  name: eraser
  namespace: default
  labels:
    name: eraser
spec:
  containers:
  - name: eraser
    image: ss104301/eraser
    resources:
      limits:
        memory: "10Mi"
        cpu: "50m"
    securityContext:
        privileged: true
    env:
    - name: PATH
      value: /usr/local/bin
  hostIPC: true
  hostNetwork: true
  hostPID: true
